### ISSUE TITLE
Why is this on Github?

### ISSUE THREAD

**Issue by ghost** [Kreyren/transgenders#3]
I mean seriously,who the heck looks on github for the search term "transgender"?
I mean most people would just look somewhere else about a article about that,I don't really think that anyone will look on Github for that.
I mean it's cool that you did that,but why not on a different site?

**Comment by Kreyren** [comment]
There is already a lots of articles about the subject, but they are usually over-complicated or full of false information.

So i decided to solve that issue my way and put it on GitHub.

Where the motivation is that people usually overreact when they encounter a transgender and have uncomfortable questions which wasn't great for the mental health of said group so this is intended to reduce them.

**Comment by ghost** [comment]
If I think about it,if this wasn't on Github then I wouldn't have found it.
Thanks for this good Project dude!

**Comment by Kreyren** [comment]
^-^

Btw. Contributions appreciated if you find any inaccuracy or something to improve.

**Comment by ghost** [comment]
I don't know much about transgender,so I can't say if anything here is inaccurate.
Btw how do you get the information?
Do you know a transgender person or are you a transgender yourself or do you look it up online?

**Comment by Kreyren** [comment]
> Btw how do you get the information? @Toadfield

Personal research + discussion with transgenders

> Do you know a transgender person or are you a transgender yourself or do you look it up online? @Toadfield

I know few and i am in contact with at least 2 most of the time ^-^ They are generally nice people to have around.

EDIT: As mentioned in the project README i ain't transgeneder.
